### ISSUE TITLE
Spelling error or suggestion in the Country input

### ISSUE THREAD

**Issue by Sakshi-Jangra** [puneeth-sai-k/covid-19-tracker#1]
In case of misspelling the country name, it must suggest the nearest response but the website doesn't behave good and hangs in the middle stage. 

- Either it must respond as **Spelling error output** or **nearest response** must be suggested.

![IMG_20210629_220920](https://user-images.githubusercontent.com/49511150/123835907-b85cb480-d926-11eb-9837-4144eb4d8e55.jpg)

Authentication Error after loading for the wrong/misspelled country name. 

![Screenshot_2021-06-29-22-09-28-392_com android chrome](https://user-images.githubusercontent.com/49511150/123835965-cd394800-d926-11eb-9d3e-6998473e0624.jpg)

- While typing the country name in the input, it must suggest country name as a drop down.

**Comment by puneeth-sai-k** [comment]
please go check now. Updated search input as per your request and maintained error handling kinda spelling mistakes etc.

**Comment by Sakshi-Jangra** [comment]
Yeah got it. Nice
